## Numpy Basics

In [1]:
import numpy as np
import time

In [3]:
num_elements = 1000000
input_array = np.arange(num_elements)
print(input_array)
print(input_array.shape)

[     0      1      2 ... 999997 999998 999999]
(1000000,)


<b>np.arange</b> is one of the routines to create arrays in NumPy. It returns an array (an instance of ndarray) of evenly spaced values.

In [8]:
print(np.arange(5)) # the i begins in 0

[0 1 2 3 4]


In [9]:
print(np.arange(2,10)) # (start, stop)

[2 3 4 5 6 7 8 9]


In [16]:
start_time = time.time()
return_array = [0] * len(input_array)
for k, v in enumerate(input_array): # populates the empty array
    return_array[k] = v * v
print(time.time() - start_time)

0.363400936126709


In [17]:
print([0]*5) # creates an empty array

[0, 0, 0, 0, 0]


In [19]:
print(return_array[2]) # sample of populated array

4


In [21]:
start_time = time.time()
return_array_vectorized = np.power(input_array,2) # (base, power)
print(time.time() - start_time)

0.021133899688720703


### Array operations

In [28]:
np.zeros(2) # creates and empty array

array([0., 0.])

In [26]:
np.identity(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.ones((2,3), dtype=np.int16) # dtype specifies the type of data

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [32]:
array_1 = np.array([[1,2], [3,4], [5,6]]) # creates an array
array_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
print(array_1.size) # number of total elements
print(array_1.shape)
print(array_1.ndim) # number of axes or dimensions (i.e. x and y) 
print(array_1.itemsize) # number of bytes of each element (e.g. int is 8)
print(array_1.dtype)
print(array_1.nbytes) # 48 = 6 (elements in array) X 8 (itemsize)

6
(3, 2)
2
8
int64
48


In [36]:
array_1[1,1] # row, col

4

In [39]:
array_1[:,1] # for all rows (:) select the column 1

array([2, 4, 6])

In [41]:
array_1[1] # get row 1

array([3, 4])

In [42]:
array_1[0][1] # select a specific element

2

In [ ]:
array_1[:]